twitter:
  access_token : '778416628090351616-RSgW3Gi4FvlgxdI0L0LToTalRtXV450'
  access_secret : 'NbzmypwIj5CoImRIwGs8NQiu2Yl6wTtzp7fkicURPLfi7'
  consumer_key : 'eoUh6hm3Nvk4M0DCVjq0HJ2AU'
  consumer_secret : 'PrjgcsbR6N1hwPxzkhh4bzC5vXJunoqGz6CDrlXHtoKG8DaZQm'
  path : '/root/Documentos/app/venv/source/files/'
